### ISSUE TITLE
php flarum queue: work command error

### ISSUE THREAD

**Issue by ghost** [blomstra/flarum-redis#2]
When I type "php flarum queue: work" command, there are error logs.

```
[2020-05-22 15:48:37] production.ERROR: Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [Flarum\Post\CommentPost]. in /var/www/sourceturk/flarum/vendor/illuminate/database/Eloquent/Builder.php:452
Stack trace:
#0 /var/www/sourceturk/flarum/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(85): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 /var/www/sourceturk/flarum/vendor/illuminate/queue/SerializesAndRestoresModelIdentifiers.php(55): FoF\FollowTags\Jobs\SendNotificationWhenReplyIsPosted->restoreModel()
#2 /var/www/sourceturk/flarum/vendor/illuminate/queue/SerializesModels.php(45): FoF\FollowTags\Jobs\SendNotificationWhenReplyIsPosted->getRestoredPropertyValue()
#3 [internal function]: FoF\FollowTags\Jobs\SendNotificationWhenReplyIsPosted->__wakeup()
#4 /var/www/sourceturk/flarum/vendor/illuminate/queue/CallQueuedHandler.php(146): unserialize()
#5 /var/www/sourceturk/flarum/vendor/illuminate/queue/Jobs/Job.php(172): Illuminate\Queue\CallQueuedHandler->failed()
#6 /var/www/sourceturk/flarum/vendor/illuminate/queue/FailingJob.php(33): Illuminate\Queue\Jobs\Job->failed()
#7 /var/www/sourceturk/flarum/vendor/illuminate/queue/CallQueuedHandler.php(131): Illuminate\Queue\FailingJob::handle()
#8 /var/www/sourceturk/flarum/vendor/illuminate/queue/CallQueuedHandler.php(45): Illuminate\Queue\CallQueuedHandler->handleModelNotFound()
#9 /var/www/sourceturk/flarum/vendor/illuminate/queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call()
#10 /var/www/sourceturk/flarum/vendor/illuminate/queue/Worker.php(327): Illuminate\Queue\Jobs\Job->fire()
#11 /var/www/sourceturk/flarum/vendor/illuminate/queue/Worker.php(277): Illuminate\Queue\Worker->process()
#12 /var/www/sourceturk/flarum/vendor/illuminate/queue/Worker.php(118): Illuminate\Queue\Worker->runJob()
#13 /var/www/sourceturk/flarum/vendor/illuminate/queue/Console/WorkCommand.php(102): Illuminate\Queue\Worker->daemon()
#14 /var/www/sourceturk/flarum/vendor/illuminate/queue/Console/WorkCommand.php(86): Illuminate\Queue\Console\WorkCommand->runWorker()
#15 [internal function]: Illuminate\Queue\Console\WorkCommand->handle()
#16 /var/www/sourceturk/flarum/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array()
#17 /var/www/sourceturk/flarum/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#18 /var/www/sourceturk/flarum/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod()
#19 /var/www/sourceturk/flarum/vendor/illuminate/container/Container.php(572): Illuminate\Container\BoundMethod::call()
#20 /var/www/sourceturk/flarum/vendor/illuminate/console/Command.php(183): Illuminate\Container\Container->call()
#21 /var/www/sourceturk/flarum/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#22 /var/www/sourceturk/flarum/vendor/illuminate/console/Command.php(170): Symfony\Component\Console\Command\Command->run()
#23 /var/www/sourceturk/flarum/vendor/symfony/console/Application.php(1019): Illuminate\Console\Command->run()
#24 /var/www/sourceturk/flarum/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#25 /var/www/sourceturk/flarum/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#26 /var/www/sourceturk/flarum/vendor/flarum/core/src/Console/Server.php(44): Symfony\Component\Console\Application->run()
#27 /var/www/sourceturk/flarum/flarum(24): Flarum\Console\Server->listen()
#28 {main}  
```

**Comment by luceos** [comment]
Seems to try to send notifications for a post that has already been deleted. This happens when you start the worker way after configuring to use it.

Not an issue with this package.
